### PR TITLE
Update TagTemplate.tid

### PR DESCRIPTION
**Pull request by t5a**
recommend condensing sets into vars widget.

### CODE REVIEW

**Comment by t5a** [comment]
I just can't get it right. I will close this until I can figure out how to do the pull request without adding that stupid line feed to the end of the file every time I try to do a pull request.

**Comment by sukima** [comment]
Did you see the animation I posted? `git add --patch` and say no to the ending line.

**Comment by sukima** [comment]
@Infurnoape, Here is how I applied this change without the ending line and updated the original Pull Request [#2471](https://github.com/Jermolene/TiddlyWiki5/pull/2471):

[asciicast](https://asciinema.org/a/9xgk6cmxlgokdlbf0ezo66v4r)

**Comment by t5a** [comment]
I honestly don't know what system you are using. It's not recognizable to me. I can only access github online, and it doesn't look anything like your video...

Happy Connecting. Sent from my Sprint Samsung Galaxy S® 5

-------- Original message --------

**Comment by sukima** [comment]
@Infurnoape Git is what GitHub is based on. In fact GitHub website only offers a small subset of tools that Git has.

Using the website to edit files will _never_ get rid of the ending line problem. This is because the de-facto standard for source code is to always end the file with a new line. This convention is built into the GitHub web client. The files don't have the ending new line because they were originally created/edited with editors that do not support (or care about) that social convention. (This is why you may see odd red glyphs at the end of files on the website to emphasize that the original author of the file is ignoring this convention.)

As you advance in working with code you may quickly find the web interface limiting. This is when you level up and use a Desktop Git client. In the animation above I'm using the main Git program but GitHub developed a desktop GUI client for those who need something before they level up to the command line.

Here is how GitHub explains you advance beyond: https://help.github.com/articles/set-up-git/#platform-windows

**Pull request closed without merging**
